server:
  port: 8080
  auth:
    basic:
      users:
        - username: user
          password: pass
integration:
  toughJet:
    url: http://tough-jet.com
    apiKey: "dGVzdC1hcGk="
    connectionTimeout: PT1S
    requestTimeout: PT2S
  crazyAir:
    url: http://crazy-air.com
    apiKey: "Y3JhenktYW="
    connectionTimeout: PT1S
    requestTimeout: PT2S